- name: Install git from apt
  apt:
    pkg: git
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Make sure ~/.ssh exists
  file:
    state: directory
    path: "{{github_user_home_dir}}/.ssh"
    owner: "{{github_user}}"
    group: "{{github_user}}"
    mode: 0700

- name: Ensure github.com is a known host
  lineinfile:
    state: present
    create: yes
    owner: "{{github_user}}"
    group: "{{github_user}}"
    mode: 0600
    dest: "{{github_user_home_dir}}/.ssh/known_hosts"
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Copy private key as github_user's id_rsa
  copy:
    content: "{{github_private_key}}"
    dest: "{{github_user_key_file}}"
    owner: "{{github_user}}"
    group: "{{github_user}}"
    mode: 0600
