---

# https://www.kernel.org/pub/software/scm/git/docs/v1.7.9/gitcredentials.html
# Alternate approach?:
# If the GIT_ASKPASS environment variable is set, the program specified by the variable is invoked.
# A suitable prompt is provided to the program on the command line, and the user’s input is read from its standard output.

- name: Put an insecure netrc file on disk becase some tools are poorly written and don't support git over ssh.  I don't like doing this.  If you have a better idea (I couldn't get git credential helpers to work appropriately), please implement it.
  template:
    src: .net.rc.j2
    dest: "/home/{{ git_user }}/.netrc"
    owner: "{{ git_user }}"
    group: "{{ git_user }}"
    mode: 0600

